/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    invitations: Invitation;
    'otp-codes': OtpCode;
    projects: Project;
    documents: Document;
    generations: Generation;
    artifacts: Artifact;
    'glossary-terms': GlossaryTerm;
    debriefs: Debrief;
    engagements: Engagement;
    'usage-events': UsageEvent;
    activity: Activity;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    invitations: InvitationsSelect<false> | InvitationsSelect<true>;
    'otp-codes': OtpCodesSelect<false> | OtpCodesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    generations: GenerationsSelect<false> | GenerationsSelect<true>;
    artifacts: ArtifactsSelect<false> | ArtifactsSelect<true>;
    'glossary-terms': GlossaryTermsSelect<false> | GlossaryTermsSelect<true>;
    debriefs: DebriefsSelect<false> | DebriefsSelect<true>;
    engagements: EngagementsSelect<false> | EngagementsSelect<true>;
    'usage-events': UsageEventsSelect<false> | UsageEventsSelect<true>;
    activity: ActivitySelect<false> | ActivitySelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  email: string;
  role: 'interpreter' | 'admin';
  uiLocale?: ('ru' | 'en') | null;
  /**
   * P1: как вас зовут коллеги
   */
  displayName?: string | null;
  /**
   * P1: где вы обычно работаете
   */
  city?: string | null;
  /**
   * P1: свободный текст о себе
   */
  bio?: string | null;
  /**
   * P1: направленные пары. EN→RU и RU→EN — разные строки: перевод в кабину и retour это разная работа и разная ставка
   */
  languagePairs?:
    | {
        source: 'ru' | 'en' | 'de' | 'fr' | 'es' | 'it' | 'pt' | 'tr' | 'zh' | 'ar' | 'uk' | 'pl';
        target: 'ru' | 'en' | 'de' | 'fr' | 'es' | 'it' | 'pt' | 'tr' | 'zh' | 'ar' | 'uk' | 'pl';
        id?: string | null;
      }[]
    | null;
  /**
   * P1: права человека, климат, медицина, право
   */
  specializations?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  /**
   * P1: AIIC, национальные объединения
   */
  memberships?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  visibility?: {
    city?: boolean | null;
    bio?: boolean | null;
    languagePairs?: boolean | null;
    specializations?: boolean | null;
    memberships?: boolean | null;
  };
  invitedAt?: string | null;
  /**
   * Пусто — берётся общий лимит из окружения (B2)
   */
  monthlyLimitUsd?: number | null;
  updatedAt: string;
  createdAt: string;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invitations".
 */
export interface Invitation {
  id: number;
  email: string;
  /**
   * Хеш токена. Сам токен есть только в письме
   */
  tokenHash?: string | null;
  /**
   * Пусто — две недели от создания
   */
  expiresAt?: string | null;
  acceptedAt?: string | null;
  acceptedBy?: (number | null) | User;
  invitedBy?: (number | null) | User;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "otp-codes".
 */
export interface OtpCode {
  id: number;
  email: string;
  codeHash: string;
  expiresAt: string;
  attempts: number;
  consumedAt?: string | null;
  /**
   * Для ограничения частоты по адресу (A3)
   */
  requestIp?: string | null;
  /**
   * Письмо отправлено. Для неприглашённых адресов остаётся false (A4)
   */
  delivered?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  owner: number | User;
  eventName?: string | null;
  eventStartsOn?: string | null;
  eventLocation?: string | null;
  /**
   * E5: когда напомнили о разборе. Напоминаем один раз
   */
  debriefRemindedAt?: string | null;
  sourceLang: 'en' | 'de' | 'fr' | 'tr';
  targetLang: 'ru' | 'en';
  stylePreset: 'un' | 'court' | 'eu' | 'corporate';
  status: 'draft' | 'scripted' | 'ready' | 'held';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  project: number | Project;
  filename: string;
  mime?: string | null;
  bytes?: number | null;
  sha256?: string | null;
  pages?: number | null;
  /**
   * Длина извлечённого текста. Сам текст не сохраняется (F2)
   */
  extractedChars?: number | null;
  /**
   * Момент удаления оригинала из хранилища (F1)
   */
  purgedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "generations".
 */
export interface Generation {
  id: number;
  project: number | Project;
  kind: 'script' | 'audio';
  params?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  model?: string | null;
  status: 'queued' | 'running' | 'done' | 'failed';
  error?: string | null;
  chars?: number | null;
  costUsd?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artifacts".
 */
export interface Artifact {
  id: number;
  project: number | Project;
  generation?: (number | null) | Generation;
  kind: 'script' | 'ssml' | 'audio' | 'glossary';
  blobPath: string;
  bytes?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "glossary-terms".
 */
export interface GlossaryTerm {
  id: number;
  project: number | Project;
  sourceTerm: string;
  targetTerm?: string | null;
  note?: string | null;
  status: 'suggested' | 'verified' | 'from-practice';
  proposedBy?: (number | null) | User;
  verifiedBy?: (number | null) | User;
  verifiedAt?: string | null;
  /**
   * E1: термин действительно прозвучал на событии
   */
  occurredAtEvent?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "debriefs".
 */
export interface Debrief {
  id: number;
  project: number | Project;
  heldOn?: string | null;
  /**
   * E3: что было труднее всего — из этого растёт следующая подготовка
   */
  hardest?: string | null;
  /**
   * E2: чего не хватило
   */
  missingTerms?: string | null;
  /**
   * E3: чем событие разошлось с ожиданием
   */
  surprises?: string | null;
  actualPace?: ('slower' | 'as-expected' | 'faster' | 'much-faster') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "engagements".
 */
export interface Engagement {
  id: number;
  owner: number | User;
  project?: (number | null) | Project;
  title: string;
  /**
   * W1: кто заказчик
   */
  organizer?: string | null;
  heldOn: string;
  location?: string | null;
  mode: 'simultaneous' | 'rsi' | 'consecutive' | 'whispered';
  sourceLang: 'ru' | 'en' | 'de' | 'fr' | 'es' | 'it' | 'pt' | 'tr' | 'zh' | 'ar' | 'uk' | 'pl';
  targetLang: 'ru' | 'en' | 'de' | 'fr' | 'es' | 'it' | 'pt' | 'tr' | 'zh' | 'ar' | 'uk' | 'pl';
  /**
   * W5: как прошло, 1–5
   */
  wentHow?: number | null;
  /**
   * W5: не разбор. Сюда пишут то, что не стыдно показать команде
   */
  wentText?: string | null;
  /**
   * W4: только текст. Спикеры не пользователи сервиса, их согласия у нас нет
   */
  speakers?:
    | {
        name: string;
        organization?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * W6. Уровень «заказчику» добавится сюда, когда появится сторона заказчика
   */
  visibility: 'private' | 'team';
  /**
   * W3: кто ещё переводил
   */
  team?:
    | {
        name: string;
        /**
         * По нему связываем с учётной записью
         */
        email?: string | null;
        /**
         * Связь появляется, когда адрес совпал
         */
        user?: (number | null) | User;
        /**
         * Кабина или роль
         */
        booth?: string | null;
        status: 'listed' | 'invited' | 'reminded' | 'confirmed' | 'disputed' | 'withdrawn';
        confirmedAt?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usage-events".
 */
export interface UsageEvent {
  id: number;
  user?: (number | null) | User;
  project?: (number | null) | Project;
  kind: 'script' | 'audio';
  chars: number;
  costUsd: number;
  tier?: string | null;
  voices?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity".
 */
export interface Activity {
  id: number;
  user?: (number | null) | User;
  project?: (number | null) | Project;
  step:
    | 'project_created'
    | 'document_uploaded'
    | 'script_generated'
    | 'audio_generated'
    | 'glossary_exported'
    | 'debrief_filled'
    | 'engagement_created'
    | 'invite_sent'
    | 'invite_accepted';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'invitations';
        value: number | Invitation;
      } | null)
    | ({
        relationTo: 'otp-codes';
        value: number | OtpCode;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'generations';
        value: number | Generation;
      } | null)
    | ({
        relationTo: 'artifacts';
        value: number | Artifact;
      } | null)
    | ({
        relationTo: 'glossary-terms';
        value: number | GlossaryTerm;
      } | null)
    | ({
        relationTo: 'debriefs';
        value: number | Debrief;
      } | null)
    | ({
        relationTo: 'engagements';
        value: number | Engagement;
      } | null)
    | ({
        relationTo: 'usage-events';
        value: number | UsageEvent;
      } | null)
    | ({
        relationTo: 'activity';
        value: number | Activity;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  email?: T;
  role?: T;
  uiLocale?: T;
  displayName?: T;
  city?: T;
  bio?: T;
  languagePairs?:
    | T
    | {
        source?: T;
        target?: T;
        id?: T;
      };
  specializations?:
    | T
    | {
        name?: T;
        id?: T;
      };
  memberships?:
    | T
    | {
        name?: T;
        id?: T;
      };
  visibility?:
    | T
    | {
        city?: T;
        bio?: T;
        languagePairs?: T;
        specializations?: T;
        memberships?: T;
      };
  invitedAt?: T;
  monthlyLimitUsd?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invitations_select".
 */
export interface InvitationsSelect<T extends boolean = true> {
  email?: T;
  tokenHash?: T;
  expiresAt?: T;
  acceptedAt?: T;
  acceptedBy?: T;
  invitedBy?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "otp-codes_select".
 */
export interface OtpCodesSelect<T extends boolean = true> {
  email?: T;
  codeHash?: T;
  expiresAt?: T;
  attempts?: T;
  consumedAt?: T;
  requestIp?: T;
  delivered?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  owner?: T;
  eventName?: T;
  eventStartsOn?: T;
  eventLocation?: T;
  debriefRemindedAt?: T;
  sourceLang?: T;
  targetLang?: T;
  stylePreset?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  project?: T;
  filename?: T;
  mime?: T;
  bytes?: T;
  sha256?: T;
  pages?: T;
  extractedChars?: T;
  purgedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "generations_select".
 */
export interface GenerationsSelect<T extends boolean = true> {
  project?: T;
  kind?: T;
  params?: T;
  model?: T;
  status?: T;
  error?: T;
  chars?: T;
  costUsd?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artifacts_select".
 */
export interface ArtifactsSelect<T extends boolean = true> {
  project?: T;
  generation?: T;
  kind?: T;
  blobPath?: T;
  bytes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "glossary-terms_select".
 */
export interface GlossaryTermsSelect<T extends boolean = true> {
  project?: T;
  sourceTerm?: T;
  targetTerm?: T;
  note?: T;
  status?: T;
  proposedBy?: T;
  verifiedBy?: T;
  verifiedAt?: T;
  occurredAtEvent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "debriefs_select".
 */
export interface DebriefsSelect<T extends boolean = true> {
  project?: T;
  heldOn?: T;
  hardest?: T;
  missingTerms?: T;
  surprises?: T;
  actualPace?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "engagements_select".
 */
export interface EngagementsSelect<T extends boolean = true> {
  owner?: T;
  project?: T;
  title?: T;
  organizer?: T;
  heldOn?: T;
  location?: T;
  mode?: T;
  sourceLang?: T;
  targetLang?: T;
  wentHow?: T;
  wentText?: T;
  speakers?:
    | T
    | {
        name?: T;
        organization?: T;
        id?: T;
      };
  visibility?: T;
  team?:
    | T
    | {
        name?: T;
        email?: T;
        user?: T;
        booth?: T;
        status?: T;
        confirmedAt?: T;
        note?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usage-events_select".
 */
export interface UsageEventsSelect<T extends boolean = true> {
  user?: T;
  project?: T;
  kind?: T;
  chars?: T;
  costUsd?: T;
  tier?: T;
  voices?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity_select".
 */
export interface ActivitySelect<T extends boolean = true> {
  user?: T;
  project?: T;
  step?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}